### ISSUE TITLE
Does this need to be in the ES spec?

### ISSUE THREAD

**Issue by domenic** [nodejs/dynamic-modules#1]
I was always under the impression that hosts could create subclasses of AMR without needing to get TC39 consensus. That was certainly the plan for the web, e.g. for WebAssembly.

Maybe it'd be better to just work on a small one-line patch to make that explicitly allowed? Then Node could define its own "Node.js module record" which is basically Dynamic Module Record but without the awkward indirection to a host hook; you'd just inline the relevant logic instead.

Apologies if I'm misunderstanding the proposal in some way.

**Comment by guybedford** [comment]
I was initially hoping to make a short PR, but one of the key things that isn’t currently possible is the late definition of export bindings while retaining execution order, and there’s no way to do this in v8 right now in Node.js, and I don’t see another way of going about that.

Certainly open to suggestions too, but it does seem generally important to me.

**Comment by domenic** [comment]
I don't quite understand. The entire contents of https://guybedford.github.io/proposal-dynamic-modules/ is a new module record type.

If we work under my assumption that you don't need to change Ecma-262 to introduce new module record types, then, what spec change would be required?

It sounds like what you're really after is for V8 to implement a new module record type, or to have a more customizable way of introducing new module record types through the V8 API. But that's not really related to the spec, and doesn't require changing Ecma-262.

**Comment by guybedford** [comment]
@domenic the interaction between the dynamic modules and the rest of the ES spec hits a few boundaries that are quite grey in terms of whether they are valid if implementing this as a non 262 spec.

* Creating let-style module bindings lazily when resolveExport is called to a dynamic module lexical scope that then link into the module instantiation process.
* Late defining exported bindings on a module during execution, including adding additional named exports to namespace exotic objects after their initial creation.

There may well be other concerns implementors would have in terms of spec validity here as well that would only be discovered during that process.

Neither the above, nor the unknown implementor concerns are obvious that they are possible if approaching this as an "addon" to the JS spec.

In addition, ECMA 262 should be serving implementations in terms of supporting the engine semantics they need. Interfacing between source text modules and non source text modules does seem a pretty fundamental feature. And this is quite an important engine semantic to be clear on what is and isn't possible.

**Comment by guybedford** [comment]
I've added an FAQ section on this in https://github.com/guybedford/proposal-dynamic-modules#could-dynamic-module-records-not-be-defined-outside-of-ecma-262.

**Comment by guybedford** [comment]
Another thing I've just added here - there is some book-keeping required to ensure module namespace objects of star export modules include the dynamic module export names, which involves a minor spec change.

**Comment by domenic** [comment]
OK. But those are solely concerns of this new type of module record, which should be worked out by whoever implements that module record. They are not part of the base language.

Your point about working out implementer concerns further suggests to me this is a good discussion to have with implementers, but not for the whole committee to advance through the proposal process and make a part of the language.

At this point my understanding of this proposal leads me to oppose it as being part of the language spec, as opposed to e.g. the Node.js documentation or a V8 design doc. (I would be fine with a spec PR to add a single parameter to GetExportedNames though, as that seems to be the only impact on the existing spec infrastructure.)

**Comment by guybedford** [comment]
@domenic that could well be a good approach, and I'd be happy to go in that direction if it is the best way forward here.

That said, it doesn't seem an obvious assessment to me... the integration is quite detailed and to repeat myself - it doesn't seem clear that the spec would support these things. We can't just have an external spec go and change lexical bindings and fields of internal objects. It's like a private interface from a spec perspective surely?

I think the TC39 process would help to inform this judgement.

**Comment by domenic** [comment]
Whether the spec supports certain operations or not isn't terribly relevant to your work though.* What's relevant is whether Node.js can implement something like this (i.e. with the same observable effects) in its host platforms (V8, ChakraCore). That's a great conversation to have with those implementers, but not one that impacts the language specification.

* For the record, it does: you've written them down in spec language.

**Comment by caridy** [comment]
I think the only reason for this to be in 262 is if we want to generalize this and expose it to user-land as a reflection API, which is something that we want to do at some point. I have mentioned some of that in the Realms presentation, we definitely need folks exploring this.

If it is a reflection API for dynamic modules, node can use it, wasm, and others can use it as well. It seems relevant from that point of view.

**Comment by domenic** [comment]
Sure. But that would be a separate proposal, which would have its own gauntlet to pass through (e.g. it's in conflict with the current plans of the WebAssembly Community Group).

**Comment by guybedford** [comment]
This now lives as a Node spec at https://github.com/nodejs/dynamic-modules.
