### ISSUE TITLE
Binding questions

### ISSUE THREAD

**Issue by robpalme** [nodejs/dynamic-modules#8]
> **Why not support constant bindings?**
> These bindings effectively behave like let bindings. Constant bindings would provide utility if there were a means to mutate them, but that currently isn't possible in this spec approach.

I'd suggest both the question and answer here need elaboration.

# Question

I interpret the question as asking:  _"Why not snapshot the value of the dynamic module's bindings post-execution and then mark them as non-writable thereafter?"_

Was this the intention?

# Answer

This answer raises a bunch of questions:

1. Are the bindings live?   The wording kinda implies there is no means to mutate them.
   1. If the CJS export property changes value post-execution, is this observed via the ESM consumers of named imports?
   2. Is the value changed observed for the namespace object?
2. Can ESM importers mutate the shared binding's values?  The wording is ambiguous on the user's point of view.
3. Can other dynamic require()-ers of a dynamic module mutate the shared binding's values observed by ESM? e.g.

```javascript
// b.js
const other = require("a.js");
other.existingProp = "new value";
```

4. What happens if a dynamic module calls `Object.defineProperty(exports, "existingProp", ...)` post-execution?  Is this observable to ES importers?

**Comment by guybedford** [comment]
The question was kind of eluding to the fact that in the original dynamic modules proposal, the goal was to capture all the ES module semantics programatically - https://gist.github.com/dherman/fbf3077a2781df74b6d8, including "const".

The question does effectively translate into exactly what you have written though!

> Are the bindings live?

Yes, the current goal is for the dynamic modules API to support mutating bindings at any time.

> Can ESM importers mutate the shared binding's values?

This would only be exposed through the C++ API side, so no. Other than that it behaves like any other ES module. Updates can only happen internally just like you can only update ES module bindings within the module itself.

> Can other dynamic require()-ers of a dynamic module mutate the shared binding's values observed by ESM? e.g.

This is host-defined from this spec perspective. Tricks could be done, yes, but I'm not advocating them personally. When it comes to the actual CommonJS integration my opinion is that snapshotting should be all that is done and that that makes sense to users. Anything more seems like it could introduce observable issues breaking backwards compat or cause performance issues.

> What happens if a dynamic module calls Object.defineProperty(exports, "existingProp", ...) post-execution? Is this observable to ES importers?

Again, this is a question for the CommonJS integration over this spec. I'd be strongly against turning all CommonJS modules into proxies though.

**Comment by guybedford** [comment]
@robpalme and thanks for putting some thought to this :)

**Comment by robpalme** [comment]
Cool. So to confirm my understanding:  bindings introduced by dynamic modules are capable of the same live value updates that source text modules support, but the probable/advocated implementation of this in Node.js will not make use of that ability; instead the binding names and values will be one-time copied into the namespace object post-evaluation.

This creates a model where the CJS `module. exports` value is distinct from the corresponding namespace object. And there is some well-defined snapshotting process that runs post-evaluation. Probably it has conditional behaviour based on whether `module.exports` is a function or not.

**Comment by guybedford** [comment]
> bindings introduced by dynamic modules are capable of the same live value updates that source text modules support, but the probable/advocated implementation of this in Node.js will not make use of that ability; instead the binding names and values will be one-time copied into the namespace object post-evaluation.

Yes, exactly!

> This creates a model where the CJS module. exports value is distinct from the corresponding namespace object. And there is some well-defined snapshotting process that runs post-evaluation. Probably it has conditional behaviour based on whether module.exports is a function or not.

We have set this up in Node core already for core modules and it is basically - `{ ...exports, ...{ default: exports } }`. Function conditional behaviours haven't been discussed deeply.
